version: '3.8'

services:
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    volumes:
     - ./db_volumes/conf.d:/etc/mysql/conf.d
     - ./db_volumes/data:/var/lib/mysql
     - ./db_volumes/initdb.d:/docker-entrypoint-initdb.d
    ports:
     - '3307:3306'
  redis:
    image: redis:latest
    command: redis-server --requirepass pnf404 --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6378:6379
    environment:
      TZ: Asia/Seoul